version: '3'
services:
        app1:
                image:  amiraothman/java-app1
                ports:
                        -       "4444:8080"
                container_name: java-app1
  
        app2:
                build:  ./Java-testapp-master2
                ports:
                        -       "5555:8080"
                container_name: Java-testapp-master2

        reverse-proxy:
                image:  amiraothman/reverse-proxy
                ports:
                        -       "3333:80"
                container_name: reverse-proxy
                links:
                        -       app1
                        -       app2
